package biztrackme.client;

import biztrackme.common.Customer;
import biztrackme.common.Product;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eran
 */
public class ClientUI extends javax.swing.JFrame {
  
  ClientController client;
  DefaultTableModel prodModel = new DefaultTableModel();
  DefaultTableModel custModel = new DefaultTableModel();;

  /**
   * Creates new form ClientUI
   */
  public ClientUI() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabPane = new javax.swing.JTabbedPane();
    welcomePane = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel3 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    bizTrackLogo = new javax.swing.JLabel();
    prodPane = new javax.swing.JScrollPane();
    prodTable = new javax.swing.JTable();
    custPane = new javax.swing.JScrollPane();
    custTable = new javax.swing.JTable();
    addPane = new javax.swing.JPanel();
    addProduct = new javax.swing.JPanel();
    prodName = new javax.swing.JTextField();
    prodSKU = new javax.swing.JTextField();
    prodPrice = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    prodSubmit = new javax.swing.JButton();
    prodStatus = new javax.swing.JLabel();
    prodClear = new javax.swing.JButton();
    addCustomer = new javax.swing.JPanel();
    jLabel9 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    custStatus = new javax.swing.JLabel();
    custAddress = new javax.swing.JTextField();
    custName = new javax.swing.JTextField();
    custPhone = new javax.swing.JTextField();
    custSubmit = new javax.swing.JButton();
    custClear = new javax.swing.JButton();
    menuBar = new javax.swing.JMenuBar();
    menuFile = new javax.swing.JMenu();
    searchCust = new javax.swing.JMenuItem();
    searchProd = new javax.swing.JMenuItem();
    fileRefresh = new javax.swing.JMenuItem();
    menuRefresh = new javax.swing.JMenuItem();
    menuAbout = new javax.swing.JMenu();
    aboutBizTrackME = new javax.swing.JMenuItem();

    setTitle("BizTrackME");
    setName("BizTrackME"); // NOI18N

    jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
    jLabel1.setText("Welcome to BizTrackME!");

    jTextArea1.setEditable(false);
    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jTextArea1.setText("This product is considered to be in active beta. Please be sure to\nreport any bugs encountered to our support center. Otherwise, \nuse the tabs above to get started and have fun out there!");

    jLabel3.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
    jLabel3.setText("version 1.0.1132014");

    jPanel1.setBackground(new java.awt.Color(51, 51, 51));
    jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

    bizTrackLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biztrackme/client/BizTrackME_Logo.png"))); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(bizTrackLogo)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(30, 30, 30)
        .addComponent(bizTrackLogo)
        .addContainerGap(18, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout welcomePaneLayout = new javax.swing.GroupLayout(welcomePane);
    welcomePane.setLayout(welcomePaneLayout);
    welcomePaneLayout.setHorizontalGroup(
      welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePaneLayout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addGroup(welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, Short.MAX_VALUE)
          .addComponent(jTextArea1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, welcomePaneLayout.createSequentialGroup()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3)))
        .addGap(35, 35, 35))
    );
    welcomePaneLayout.setVerticalGroup(
      welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(welcomePaneLayout.createSequentialGroup()
        .addGap(34, 34, 34)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(welcomePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(38, Short.MAX_VALUE))
    );

    tabPane.addTab("Start Page", welcomePane);

    prodTable.setModel(prodModel);
    prodTable.setEnabled(false);
    prodPane.setViewportView(prodTable);

    tabPane.addTab("Products", prodPane);

    custTable.setEnabled(false);
    custPane.setViewportView(custTable);

    tabPane.addTab("Customers", custPane);

    addProduct.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Product"));

    jLabel4.setText("Name");

    jLabel5.setText("SKU");

    jLabel6.setText("Price");

    prodSubmit.setText("Add Product");
    prodSubmit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        prodSubmitActionPerformed(evt);
      }
    });

    prodStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    prodClear.setText("Clear");
    prodClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        prodClearActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout addProductLayout = new javax.swing.GroupLayout(addProduct);
    addProduct.setLayout(addProductLayout);
    addProductLayout.setHorizontalGroup(
      addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addProductLayout.createSequentialGroup()
        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(prodName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(addProductLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(jLabel5)
              .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(prodSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(prodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addGap(18, 18, 18)
        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(prodStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addProductLayout.createSequentialGroup()
            .addGap(0, 7, Short.MAX_VALUE)
            .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(prodClear, javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(prodSubmit, javax.swing.GroupLayout.Alignment.TRAILING))))
        .addContainerGap())
    );
    addProductLayout.setVerticalGroup(
      addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addProductLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(prodStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(prodName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(prodSKU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel5)
          .addComponent(prodClear))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(prodSubmit)
          .addComponent(prodPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel6))
        .addContainerGap(13, Short.MAX_VALUE))
    );

    addCustomer.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Customer"));

    jLabel9.setText("Phone");

    jLabel7.setText("Name");

    jLabel8.setText("Address");

    custStatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

    custSubmit.setText("Add Customer");
    custSubmit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        custSubmitActionPerformed(evt);
      }
    });

    custClear.setText("Clear");
    custClear.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        custClearActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout addCustomerLayout = new javax.swing.GroupLayout(addCustomer);
    addCustomer.setLayout(addCustomerLayout);
    addCustomerLayout.setHorizontalGroup(
      addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addCustomerLayout.createSequentialGroup()
        .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addGap(27, 27, 27)
            .addComponent(jLabel7))
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel8))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCustomerLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel9)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(custStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addComponent(custAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(custClear))
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(custSubmit)))
        .addContainerGap())
    );
    addCustomerLayout.setVerticalGroup(
      addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addCustomerLayout.createSequentialGroup()
        .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addCustomerLayout.createSequentialGroup()
            .addGap(3, 3, 3)
            .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(jLabel7)
              .addComponent(custName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addComponent(custStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(custClear)
          .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(custAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel8)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(addCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel9)
            .addComponent(custPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(custSubmit))
        .addContainerGap(35, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout addPaneLayout = new javax.swing.GroupLayout(addPane);
    addPane.setLayout(addPaneLayout);
    addPaneLayout.setHorizontalGroup(
      addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addPaneLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(addCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(addProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    addPaneLayout.setVerticalGroup(
      addPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(addPaneLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(addCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    tabPane.addTab("Add Records", addPane);

    menuFile.setText("File");

    searchCust.setText("Search for Customer");
    searchCust.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchCustActionPerformed(evt);
      }
    });
    menuFile.add(searchCust);

    searchProd.setText("Search for Product");
    searchProd.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        searchProdActionPerformed(evt);
      }
    });
    menuFile.add(searchProd);

    fileRefresh.setText("Refresh");
    fileRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fileRefreshActionPerformed(evt);
      }
    });
    menuFile.add(fileRefresh);

    menuRefresh.setText("Exit");
    menuRefresh.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuRefreshActionPerformed(evt);
      }
    });
    menuFile.add(menuRefresh);

    menuBar.add(menuFile);

    menuAbout.setText("About");

    aboutBizTrackME.setText("About BizTrackME");
    aboutBizTrackME.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        aboutBizTrackMEActionPerformed(evt);
      }
    });
    menuAbout.add(aboutBizTrackME);

    menuBar.add(menuAbout);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(tabPane, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void fileRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileRefreshActionPerformed
    client.populateStores();
    this.refreshCustomers();
    this.refreshProducts();
  }//GEN-LAST:event_fileRefreshActionPerformed

  private void prodSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSubmitActionPerformed
    client.addProduct( prodStatus, prodName, prodSKU, prodPrice );
    this.refreshProducts();
  }//GEN-LAST:event_prodSubmitActionPerformed

  private void custSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custSubmitActionPerformed
    client.addCustomer(custStatus, custName, custAddress, custPhone);
    this.refreshCustomers();
  }//GEN-LAST:event_custSubmitActionPerformed

  private void menuRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRefreshActionPerformed
    System.exit(0);
  }//GEN-LAST:event_menuRefreshActionPerformed

  private void aboutBizTrackMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutBizTrackMEActionPerformed
    JOptionPane.showMessageDialog(
      this, 
      "BizTrackME- Business software for the new millenium!\n" +
      "Written by: Eran Schoellhorn\n" +
      "IT351: Advanced Java Programming\n" + 
      "Version: 1.0.1142014", "BizTrackME", 3);
  }//GEN-LAST:event_aboutBizTrackMEActionPerformed

  private void custClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custClearActionPerformed
    custName.setText("");
    custPhone.setText("");
    custAddress.setText("");
  }//GEN-LAST:event_custClearActionPerformed

  private void prodClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodClearActionPerformed
    prodName.setText("");
    prodSKU.setText("");
    prodPrice.setText("");
  }//GEN-LAST:event_prodClearActionPerformed

  private void searchCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustActionPerformed
    String query = JOptionPane.showInputDialog(
      this, 
      "Please enter the customer's name you wish to search for."
    );
    JOptionPane.showMessageDialog(this, client.search("cust", query) );
  }//GEN-LAST:event_searchCustActionPerformed

  private void searchProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchProdActionPerformed
    String query = JOptionPane.showInputDialog(
      this, 
      "Please enter the product name you wish to search for."
    );
    JOptionPane.showMessageDialog(this, client.search("prod", query) );
  }//GEN-LAST:event_searchProdActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        ClientUI ui = new ClientUI();
        
        try{
          ui.init();
          ui.setVisible(true);
        }catch(NullPointerException ex){
          JOptionPane.showMessageDialog(
            ui, 
            "Fatal error connecting to server. Is it on?", "Error!", 2
          );
          System.exit(0);
        }           
      }
    });
    
    
    
    
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuItem aboutBizTrackME;
  private javax.swing.JPanel addCustomer;
  private javax.swing.JPanel addPane;
  private javax.swing.JPanel addProduct;
  private javax.swing.JLabel bizTrackLogo;
  private javax.swing.JTextField custAddress;
  private javax.swing.JButton custClear;
  private javax.swing.JTextField custName;
  private javax.swing.JScrollPane custPane;
  private javax.swing.JTextField custPhone;
  private javax.swing.JLabel custStatus;
  private javax.swing.JButton custSubmit;
  private javax.swing.JTable custTable;
  private javax.swing.JMenuItem fileRefresh;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JMenu menuAbout;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuFile;
  private javax.swing.JMenuItem menuRefresh;
  private javax.swing.JButton prodClear;
  private javax.swing.JTextField prodName;
  private javax.swing.JScrollPane prodPane;
  private javax.swing.JTextField prodPrice;
  private javax.swing.JTextField prodSKU;
  private javax.swing.JLabel prodStatus;
  private javax.swing.JButton prodSubmit;
  private javax.swing.JTable prodTable;
  private javax.swing.JMenuItem searchCust;
  private javax.swing.JMenuItem searchProd;
  private javax.swing.JTabbedPane tabPane;
  private javax.swing.JPanel welcomePane;
  // End of variables declaration//GEN-END:variables

  /**
   * Simple init method which initializes the controller for the UI
   */
  public void init(){
    
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    
    // Initialize client controller
    client = new ClientController(); 
    
    // Populate tables
    this.refreshProducts();
    this.refreshCustomers();
    
  }
  
  /**
   * Creates and applies model for Products table
   */
  public void refreshProducts(){
    // Initialize table model
    prodModel = new DefaultTableModel();
    prodModel.setColumnIdentifiers(new String[]{"Name", "SKU", "Price"});
    for (Product p : client.getP().getRecords()) {
      prodModel.addRow(p.toString().split("\n"));
    }
    prodTable.setModel(prodModel);
  }
  
  /**
   * Creates and applies model for Customers table
   */
  public void refreshCustomers(){
    // Initialize customer model
    custModel = new DefaultTableModel();
    custModel.setColumnIdentifiers(new String[]{"Name", "Address", "Phone"});
    for (Customer c : client.getC().getRecords()) {
      custModel.addRow(c.toString().split("\n"));
    }
    custTable.setModel(custModel);
  }
  
}
